[versions]
agp = "8.13.0"
kotlin = "2.2.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.09.00"

ksp = "2.2.0-2.0.2"
hilt = "2.57.2"
hiltAndroidx = "1.3.0"
room = "2.8.3"

retrofit = "3.0.0"
okHttp = "5.1.0"
kotlinxSerialization = "1.9.0"
retrofitSerializationConverter = "3.0.0"
logginInterceptor = "5.1.0"

protoDatastore = "1.1.7"
protobuf = "0.9.4"
protobufJavalite = "4.26.1"
protobufProtoc = "4.26.1"

worker = "2.10.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-worker = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "worker" }

# Room Database
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltAndroidx" }

# HTTP Requests
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
okHttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
retrofit-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofitSerializationConverter" }
http-loggin-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logginInterceptor" }

# Proto Datastore
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinxSerialization" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "protoDatastore" }
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobufJavalite" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobufProtoc" }

hilt-worker = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltAndroidx" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
room = { id = "androidx.room", version.ref = "room" }

serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }

[bundles]
room-db = [
    "androidx-room",
    "androidx-room-ktx",
]
network = [
    "okHttp",
    "retrofit",
    "retrofit-serialization-converter",
    "http-loggin-interceptor",
    "kotlinx-serialization-json"
]
protobufDatastore = [
    "androidx-datastore",
    "protobuf-javalite",
    "protobuf-protoc",
    "kotlinx-serialization-protobuf"
]

